server:
  port: 9100
  tomcat:
    accept-count: 100
    max-connections: 1000
    max-threads: 20
    min-spare-threads: 20

spring:
  application:
    name: kafkamanager
  datasource:
    kafka-manager:
      jdbc-url: jdbc:mysql://10.100.31.9:3309/kafka_manager?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: wifiyouni
      password: PgM4xhYklOlpV3NU
      driver-class-name: org.mariadb.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:logback-spring.xml

# kafka监控
kafka-monitor:
  enabled: true
  notify-kafka:
    cluster-id: 95
    topic-name: kmo_monitor
